// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nauth_asp.DbContexts;

#nullable disable

namespace nauth_asp.Migrations
{
    [DbContext(typeof(NauthDbContext))]
    [Migration("20250903211855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nauth_asp.Models.DB_User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nauth_asp.Models.EmailAction.DB_EmailAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DB_UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("data")
                        .HasColumnType("text");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DB_UserId");

                    b.HasIndex("token")
                        .IsUnique();

                    b.ToTable("EmailActions");
                });

            modelBuilder.Entity("nauth_asp.Models.Permissions.DB_Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServiceId1")
                        .HasColumnType("bigint");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceId1");

                    b.HasIndex("key", "ServiceId")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("nauth_asp.Models.Permissions.DB_UserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("permissionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("permissionId1")
                        .HasColumnType("bigint");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.Property<long?>("userId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("permissionId");

                    b.HasIndex("permissionId1");

                    b.HasIndex("userId1");

                    b.HasIndex("userId", "permissionId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("nauth_asp.Models.Service.DB_Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.Property<long?>("userId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.HasIndex("userId1");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("nauth_asp.Models.Service.DB_UserService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("serviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("serviceId1")
                        .HasColumnType("bigint");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.Property<long?>("userId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("serviceId");

                    b.HasIndex("serviceId1");

                    b.HasIndex("userId1");

                    b.HasIndex("userId", "serviceId")
                        .IsUnique();

                    b.ToTable("UserServices");
                });

            modelBuilder.Entity("nauth_asp.Models.Session.DB_Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is2FAConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("jwtHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("serviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("serviceId1")
                        .HasColumnType("bigint");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.Property<long?>("userId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("serviceId");

                    b.HasIndex("serviceId1");

                    b.HasIndex("userId");

                    b.HasIndex("userId1");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("nauth_asp.Models.TwoFactorAuth.DB_2FAEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_2faSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("recoveryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.Property<long?>("userId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.HasIndex("userId1");

                    b.ToTable("TwoFactorAuthEntries");
                });

            modelBuilder.Entity("nauth_asp.Models.EmailAction.DB_EmailAction", b =>
                {
                    b.HasOne("nauth_asp.Models.DB_User", null)
                        .WithMany("emailActions")
                        .HasForeignKey("DB_UserId");
                });

            modelBuilder.Entity("nauth_asp.Models.Permissions.DB_Permission", b =>
                {
                    b.HasOne("nauth_asp.Models.Service.DB_Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.Service.DB_Service", "Service")
                        .WithMany("permissions")
                        .HasForeignKey("ServiceId1");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("nauth_asp.Models.Permissions.DB_UserPermission", b =>
                {
                    b.HasOne("nauth_asp.Models.Permissions.DB_Permission", null)
                        .WithMany()
                        .HasForeignKey("permissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.Permissions.DB_Permission", "permission")
                        .WithMany()
                        .HasForeignKey("permissionId1");

                    b.HasOne("nauth_asp.Models.DB_User", null)
                        .WithMany("permissions")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.DB_User", "user")
                        .WithMany()
                        .HasForeignKey("userId1");

                    b.Navigation("permission");

                    b.Navigation("user");
                });

            modelBuilder.Entity("nauth_asp.Models.Service.DB_Service", b =>
                {
                    b.HasOne("nauth_asp.Models.DB_User", null)
                        .WithMany("ownedServices")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.DB_User", "user")
                        .WithMany()
                        .HasForeignKey("userId1");

                    b.Navigation("user");
                });

            modelBuilder.Entity("nauth_asp.Models.Service.DB_UserService", b =>
                {
                    b.HasOne("nauth_asp.Models.Service.DB_Service", null)
                        .WithMany()
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.Service.DB_Service", "service")
                        .WithMany()
                        .HasForeignKey("serviceId1");

                    b.HasOne("nauth_asp.Models.DB_User", null)
                        .WithMany("services")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.DB_User", "user")
                        .WithMany()
                        .HasForeignKey("userId1");

                    b.Navigation("service");

                    b.Navigation("user");
                });

            modelBuilder.Entity("nauth_asp.Models.Session.DB_Session", b =>
                {
                    b.HasOne("nauth_asp.Models.Service.DB_Service", null)
                        .WithMany("sessions")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nauth_asp.Models.Service.DB_Service", "service")
                        .WithMany()
                        .HasForeignKey("serviceId1");

                    b.HasOne("nauth_asp.Models.DB_User", null)
                        .WithMany("sessions")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.DB_User", "user")
                        .WithMany()
                        .HasForeignKey("userId1");

                    b.Navigation("service");

                    b.Navigation("user");
                });

            modelBuilder.Entity("nauth_asp.Models.TwoFactorAuth.DB_2FAEntry", b =>
                {
                    b.HasOne("nauth_asp.Models.DB_User", null)
                        .WithMany("_2FAEntries")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nauth_asp.Models.DB_User", "user")
                        .WithMany()
                        .HasForeignKey("userId1");

                    b.Navigation("user");
                });

            modelBuilder.Entity("nauth_asp.Models.DB_User", b =>
                {
                    b.Navigation("_2FAEntries");

                    b.Navigation("emailActions");

                    b.Navigation("ownedServices");

                    b.Navigation("permissions");

                    b.Navigation("services");

                    b.Navigation("sessions");
                });

            modelBuilder.Entity("nauth_asp.Models.Service.DB_Service", b =>
                {
                    b.Navigation("permissions");

                    b.Navigation("sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
